// src/components/common/footer.tsx
export default function Footer() {
  return (
    <footer className="w-full h-[5vh] bg-[#1a1f36] border-t border-[#2d3555]">
      <div className="container mx-auto px-4 h-full flex items-center justify-center">
        <p className="text-center text-white text-sm">
          © 2024 Stjoo. All rights reserved.
        </p>
      </div>
    </footer>
  );
}

// src/components/footer.vue
<template>
  <footer class="footer-container">
    <div class="footer-content">© 2024 JooSoonTae. All Rights Reserved.</div>
  </footer>
</template>

<style scoped>
.footer-container {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 20px;
  background-color: var(--header-footer-color);
  color: var(--font-color);
  font-family: "goorm-sans-bold";
  font-size: 14px;
  box-shadow: 0 -2px 4px rgba(0, 0, 0, 0.1);
}

.footer-content {
  text-align: center;
}
</style>
